[package]
name = "fvm_sdk"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
cid = { version = "0.7.0", default-features = false }
fvm_shared = { path = "../shared" }
## num-traits; disabling default features makes it play nice with no_std.
num-traits = { version = "0.2.14", default-features = false }
lazy_static = "1.4.0"
log = "0.4.14"
thiserror = "1.0.30"
